### ISSUE TITLE
Can pybuilt be build with python 3.7?

### ISSUE THREAD

**Issue by Amjadhpc** [LoLab-VU/PyBILT#49]
Hello
The installation guide says python 3.6 is required for build pyBIlt, Can we build with python 3.7?

**Comment by blakeaw** [comment]
Hi
Ok, I finally got around to testing this. It looks like for the most part everything runs okay in python 3.7. However, I did get a couple minor errors when I ran the tests. I've opened a new issue for that (Issue https://github.com/LoLab-VU/PyBILT/issues/50), so I'm going to go ahead close this one. 

In the meantime, I think you should be able run core pybilt functionality with python 3.7. However, If you do run into other problems using pybilt with python 3.7,please either comment on the other issue (Issue https://github.com/LoLab-VU/PyBILT/issues/50) or open a new one and let me know. 

Thanks,
Blake
