### ISSUE TITLE
Area per lipid

### ISSUE THREAD

**Issue by almeida85** [LoLab-VU/PyBILT#51]
Hi,
I am using the com_trajectory.ipynb with my runs. I have a protein embeded in a heterogeneous membrane. In the notebook states: "For more accurate area per lipid estimations we reccommend using the gridding objects in the pybilt.leaflet_gridding module files." There is no pybilt.leaflet_gridding module in pybilt. Did you mean pybilt.lipid_grid module? Can you provide more details to calculate APL with this module using the notebook?

Thanks in advance,

Yasser

**Comment by blakeaw** [comment]
Hi Yasser,

Thanks for pointing this out. It is supposed to be pybilt.lipid_grid. I'll fix that in the notebook and I can also add an example use of the lipid grid based APL computation from a COMTraj object. However, I'll also point out that BilayerAnalyzer class objects already have the grid based APL as a built-in analysis protocol, abstracting away the need to do it manually (as with COMTraj objects): https://pybilt.readthedocs.io/en/latest/ba_analyses/apl_grid.html

Finally, I should note that although the grid based APL calculations can handle heterogeneous lipid mixtures, I've yet to get around to adding support for systems with embedded proteins. Therefore, the current pybilt APL tools probably won't work properly with your system (which has an embedded protein).  I've opened a new Issue https://github.com/LoLab-VU/PyBILT/issues/52 for this feature. I'll work on it, but it'll probably be a few days (or maybe longer) before I can get something implemented.

**Comment by almeida85** [comment]
Hi Blake,

thank you for your reply. Could you suggest a tool of code (if any) to estimate APL in systems with embedded proteins? I am working with CG systems, simulated during 10 us.

Best

**Comment by blakeaw** [comment]
There are a couple external programs whose methods are the inspiration for those implemented in the pybilt.lipid_grid module:
1. GridMAT-MD http://www.bevanlab.biochem.vt.edu/GridMAT-MD/
2. g_lomepro http://www3.mpibpc.mpg.de/groups/de_groot/g_lomepro.html

They both support embedded proteins. However, I think they only work with gromacs files.

**Comment by blakeaw** [comment]
Fixes included in PR https://github.com/LoLab-VU/PyBILT/pull/54

**Comment by blakeaw** [comment]
> 1. GridMAT-MD

bevanlab link for GridMAT-MD no longer works, but the GridMAT-MD program is available in GitHub: https://github.com/jalemkul/gridmat-md
