### ISSUE TITLE
File support for BilayerAnalyzer

### ISSUE THREAD

**Issue by DanielWicz** [LoLab-VU/PyBILT#59]
I'm trying to figure out which filetype in the BilayerAnalzer module, I was training to use .psf/.gro as structure and .dcd/.xtc as trajectory, but it seems to not work. 

Could anyone explain to me what's the file time as it is not mentioned in the documentation?

**Comment by blakeaw** [comment]
Hi @DanielWicz, 
Apologies for the delay. The BilayerAnalyzer uses MDAnalysis as its backend for topology/trajectory reading and manipulation, so it should work with any of the formats supported by MDAnalysis; I'll add the links to the MDAnalysis docs below. The formats you mentioned are among those that should be supported, so I'm not sure at this point what the problem could be. If you can provide more details such as the exact error messages and the code blocks with your initialization/calls to the BilayerAnalyzer object, I'll try to figure out if it is a bug in PyBILT.   

Here are the links to supported formats in the MDAnalysis docs:
topology:  
https://www.mdanalysis.org/docs/documentation_pages/topology/init.html#id17
coordinate/trajectory:
https://www.mdanalysis.org/docs/documentation_pages/coordinates/init.html#supported-coordinate-formats

I've also opened a separate issue specifically for adding the appropriate documentation related to this issue. It is Issue https://github.com/LoLab-VU/PyBILT/issues/60
https://github.com/LoLab-VU/PyBILT/issues/60
